com.sleepycat.je.SecondaryIntegrityException: (JE 4.1.10) Secondary is corrupt: the primary record contains a key that is not present in the secondary
	at com.sleepycat.je.SecondaryDatabase.deleteKey(SecondaryDatabase.java:936)
	at com.sleepycat.je.SecondaryDatabase.updateSecondary(SecondaryDatabase.java:851)
	at com.sleepycat.je.SecondaryTrigger.databaseUpdated(SecondaryTrigger.java:41)
	at com.sleepycat.je.Database.notifyTriggers(Database.java:2016)
	at com.sleepycat.je.Cursor.putNotify(Cursor.java:1702)
	at com.sleepycat.je.Cursor.putInternal(Cursor.java:1626)
	at com.sleepycat.je.Database.putInternal(Database.java:1186)
	at com.sleepycat.je.Database.put(Database.java:1058)
	at com.sleepycat.persist.PrimaryIndex.putNoReturn(PrimaryIndex.java:479)
	at com.sleepycat.persist.PrimaryIndex.putNoReturn(PrimaryIndex.java:442)
	at edu.brown.lasvegas.lvfs.meta.MasterMetadataRepository.createNewColumnFile(MasterMetadataRepository.java:955)
	at edu.brown.lasvegas.lvfs.meta.MasterMetadataRepository.createNewColumnFileIdOnlyReturn(MasterMetadataRepository.java:961)
	at edu.brown.lasvegas.lvfs.data.DataTaskUtil.registerTemporaryFilesAsColumnFiles(DataTaskUtil.java:51)
	at edu.brown.lasvegas.lvfs.data.RecoverPartitionFromBuddyTaskRunner.runDataTask(RecoverPartitionFromBuddyTaskRunner.java:70)
	at edu.brown.lasvegas.lvfs.data.DataTaskRunner.run(DataTaskRunner.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:679)
[2012-01-24 11:12:03,734]ERROR  3490[pool-2-thread-1] - edu.brown.lasvegas.lvfs.data.DataTaskRunner.run(DataTaskRunner.java:50) - exception in runDerived()
com.sleepycat.je.SecondaryIntegrityException: (JE 4.1.10) Secondary is corrupt: the primary record contains a key that is not present in the secondary
	at com.sleepycat.je.SecondaryDatabase.deleteKey(SecondaryDatabase.java:936)
	at com.sleepycat.je.SecondaryDatabase.updateSecondary(SecondaryDatabase.java:851)
	at com.sleepycat.je.SecondaryTrigger.databaseUpdated(SecondaryTrigger.java:41)
	at com.sleepycat.je.Database.notifyTriggers(Database.java:2016)
	at com.sleepycat.je.Database.deleteInternal(Database.java:800)
	at com.sleepycat.je.Database.delete(Database.java:714)
	at com.sleepycat.persist.BasicIndex.delete(BasicIndex.java:133)
	at com.sleepycat.persist.PrimaryIndex.delete(PrimaryIndex.java:206)
	at com.sleepycat.persist.BasicIndex.delete(BasicIndex.java:124)
	at com.sleepycat.persist.PrimaryIndex.delete(PrimaryIndex.java:206)
	at edu.brown.lasvegas.lvfs.meta.MasterMetadataRepository.dropColumnFile(MasterMetadataRepository.java:979)
	at edu.brown.lasvegas.lvfs.data.DataTaskUtil.registerTemporaryFilesAsColumnFiles(DataTaskUtil.java:46)
	at edu.brown.lasvegas.lvfs.data.RecoverPartitionFromBuddyTaskRunner.runDataTask(RecoverPartitionFromBuddyTaskRunner.java:70)
	at edu.brown.lasvegas.lvfs.data.DataTaskRunner.run(DataTaskRunner.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:679)
[2012-01-24 11:12:03,754] INFO  3510[main] - edu.brown.lasvegas.lvfs.data.ImportFractureJobController.joinTasks(ImportFractureJobController.java:439) - some change on task progress: Task-9(jobId=2) type=RECOVER_PARTITION_FROM_BUDDY, progress=100.0%, status=ERROR, nodeId=1, startedTime=Tue Jan 24 11:12:03 EST 2012, finishedTime=Tue Jan 24 11:12:03 EST 2012, outputFilePaths=null, errorMessages=(JE 4.1.10) Secondary is corrupt: the primary record contains a key that is not present in the secondary
[2012-01-24 11:12:03,755]ERROR  3511[main] - edu.brown.lasvegas.lvfs.data.ImportFractureJobController.joinTasks(ImportFractureJobController.java:448) - A task reported an error! : Task-9(jobId=2) type=RECOVER_PARTITION_FROM_BUDDY, progress=100.0%, status=ERROR, nodeId=1, startedTime=Tue Jan 24 11:12:03 EST 2012, finishedTime=Tue Jan 24 11:12:03 EST 2012, outputFilePaths=null, errorMessages=(JE 4.1.10) Secondary is corrupt: the primary record contains a key that is not present in the secondary
[2012-01-24 11:12:03,755] INFO  3511[main] - edu.brown.lasvegas.lvfs.data.ImportFractureJobController.cancelAllTasks(ImportFractureJobController.java:411) - cancelling tasks...
